{
 "cells": [
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "<h2 style=\"text-align: center;\">Типы ошыбок</h2>\n",
    "\n",
    "<p>Разработка программы на любом языке программирования практически всегда бывает связана с возникновением различного рода ошибок, препятствующих получению желаемого результата.</p>\n",
    "\n",
    "<p>Обычно выделяют следующие три категории ошибок:</p>\n",
    "\n",
    "<ul>\n",
    "\t<li>синтаксические – возникают из-за синтаксических погрешностей кода</li>\n",
    "\t<li>логические – проявляются вследствие логических неточностей в алгоритме</li>\n",
    "\t<li>ошибки времени выполнения, исключения – вызваны некорректными действиями пользователя или системы</li>\n",
    "</ul>\n",
    "\n",
    "<h3 style=\"text-align: center;\">Синтаксические ошибки</h3>\n",
    "\n",
    "<p>Синтаксические ошибки являются следствием несоблюдения общепринятого синтаксиса языка.&nbsp;Другими словами, это ошибки, связанные с неправильно набранным кодом.&nbsp;Например пропуск круглой скобки, запятой или двоеточия.</p>\n",
    "\n",
    "<p>В приведенном ниже коде:</p>\n",
    "\n",
    "<pre><code class=\"language-python hljs\" data-highlighted=\"yes\"><span class=\"hljs-built_in\">print</span>(<span class=\"hljs-string\">'Hello, world!'</span></code></pre>\n",
    "\n",
    "<p>допущена одна синтаксическая ошибка: <strong>пропущена закрывающая скобка</strong>. При попытке его запуска получим:</p>\n",
    "\n",
    "<pre><code class=\"language-no-highlight hljs\">SyntaxError: '(' was never closed</code></pre>\n",
    "\n",
    "<p>В приведенном ниже коде:</p>\n",
    "\n",
    "<pre><code class=\"language-python hljs\" data-highlighted=\"yes\"><span class=\"hljs-keyword\">def</span> <span class=\"hljs-title function_\">square</span>(<span class=\"hljs-params\">num</span>)\n",
    "    <span class=\"hljs-keyword\">return</span> num ** <span class=\"hljs-number\">2</span></code></pre>\n",
    "\n",
    "<p>допущена также синтаксическая ошибка: <strong>пропущен символ двоеточия в описании функции</strong>.&nbsp;При попытке его запуска получим:</p>\n",
    "\n",
    "<pre><code class=\"language-no-highlight hljs\">    def square(num)\n",
    "                   ^\n",
    "SyntaxError: expected ':'</code></pre>\n",
    "\n",
    "<p><img alt=\"\" name=\"1 копия.png\" src=\"https://sch1998u.mskobr.ru/files/NOVOSTI/30.12.22/20211010105318.png\" width=\"150\">&nbsp; &nbsp;Синтаксические ошибки легко отлавливаются интерпретатором, который сразу же сообщает программисту о проблеме в написанном коде.&nbsp;</p>\n",
    "\n",
    "<h3 style=\"text-align: center;\">Логические ошибки</h3>\n",
    "\n",
    "<p>Логические ошибки считаются более сложными в выявлении, поскольку не отлавливаются интерпретатором. Обычно они вызваны определенным недостатком в логике программы, из-за чего результат работы программы отличается от желаемого результата.&nbsp;Возможным решением проблемы является тестирование программы на разных примерах входных данных, для которых известен правильный результат.</p>\n",
    "\n",
    "<p>В приведенном ниже коде:</p>\n",
    "\n",
    "<pre><code class=\"language-python hljs\" data-highlighted=\"yes\"><span class=\"hljs-keyword\">def</span> <span class=\"hljs-title function_\">avg</span>(<span class=\"hljs-params\">a, b</span>):\n",
    "    <span class=\"hljs-keyword\">return</span> a + b / <span class=\"hljs-number\">2</span></code></pre>\n",
    "\n",
    "<p>описана функция&nbsp;<code>avg()</code>, подсчитывающая среднее значение переданных в нее аргументов. В теле функции допущена логическая ошибка, пропущены скобки, на два должна делиться сумма чисел <code>a</code> и <code>b</code>.</p>\n",
    "\n",
    "<p>Приведенный ниже код:</p>\n",
    "\n",
    "<pre><code class=\"language-python hljs\" data-highlighted=\"yes\"><span class=\"hljs-built_in\">print</span>(avg(<span class=\"hljs-number\">6</span>, <span class=\"hljs-number\">14</span>))</code></pre>\n",
    "\n",
    "<p>выводит <strong>неверный результат</strong>:</p>\n",
    "\n",
    "<pre><code class=\"language-no-highlight hljs\">13.0</code></pre>\n",
    "\n",
    "<p>Обратите внимание на то, что приведенная выше функция <code>avg()</code> не всегда работает неверно.</p>\n",
    "\n",
    "<p>Приведенный ниже код:</p>\n",
    "\n",
    "<pre><code class=\"language-python hljs\" data-highlighted=\"yes\"><span class=\"hljs-built_in\">print</span>(avg(<span class=\"hljs-number\">0</span>, <span class=\"hljs-number\">7</span>))</code></pre>\n",
    "\n",
    "<p>выводит <strong>верный результат</strong>:</p>\n",
    "\n",
    "<pre><code class=\"language-no-highlight hljs\">3.5</code></pre>\n",
    "\n",
    "<p><img alt=\"\" name=\"1 копия.png\" src=\"https://sch1998u.mskobr.ru/files/NOVOSTI/30.12.22/20211010105318.png\" width=\"150\">&nbsp; &nbsp;Логические ошибки могут проявлять себя только при определенных условиях. Часто код с логической ошибкой может работать достаточно долго.</p>\n",
    "\n",
    "<h3 style=\"text-align: center;\">Ошибки времени выполнения</h3>\n",
    "\n",
    "<p>Исключения представляют собой еще один вид ошибок, которые проявляются в зависимости от наличия обстоятельств, меняющих ход выполнения программы. Исключения являются ошибками времени выполнения, возникающими в процессе выполнения программы и связанными с некорректностью переданных в программу данных, недоступностью ресурсов и т.д.</p>\n",
    "\n",
    "<p>Приведенный ниже код:</p>\n",
    "\n",
    "<pre><code class=\"language-python hljs\" data-highlighted=\"yes\">num1 = <span class=\"hljs-number\">10</span>\n",
    "num2 = <span class=\"hljs-number\">0</span>\n",
    "\n",
    "<span class=\"hljs-built_in\">print</span>(num1 / num2)</code></pre>\n",
    "\n",
    "<p>выводит:</p>\n",
    "\n",
    "<pre><code class=\"language-no-highlight hljs\">ZeroDivisionError: division by zero</code></pre>\n",
    "\n",
    "<p>Деление на ноль провоцирует исключительную ситуацию, которая приводит к аварийному завершению работы и выводу ошибки на экран.&nbsp;<code>ZeroDivisionError</code>&nbsp;— это название исключения, а&nbsp;<code>division by zero</code>&nbsp;— его краткое описание.</p>\n",
    "\n",
    "<p><img alt=\"\" name=\"1 копия.png\" src=\"https://sch1998u.mskobr.ru/files/NOVOSTI/30.12.22/20211010105318.png\" width=\"150\">&nbsp; &nbsp;Если мы&nbsp;хотим, чтобы программа работала с&nbsp;широким диапазоном входных данных и&nbsp;внешних условий, то&nbsp;надо учитывать исключения, программа должна их&nbsp;верно обрабатывать.</p>\n",
    "\n",
    "<p>По умолчанию при обнаружении необработанного исключения Python&nbsp;немедленно останавливает выполнение программы и&nbsp;выводит сообщение об ошибке.</p>\n"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "<h2 style=\"text-align: center;\">Обработка исключений</h2>\n",
    "\n",
    "<p>Далеко не для каждой ошибки можно выполнить обработку так, чтобы программа продолжала выполняться. Однако в некоторых случаях такая обработка может быть выполнена. Собственно, о таких потенциально \"отлавливаемых\" ошибках, их перехвате и обработке будет идти речь.</p>\n",
    "\n",
    "<p>Общая идея, заложенная в основу метода обработки исключений, такая: программный код, в котором теоретически может возникнуть ошибка, выделяется специальным образом&nbsp;– \"берется на контроль\". Если при выполнении этого программного кода ошибка не возникает, то ничего особенного не происходит. Если при выполнении \"контролируемого\" кода возникает ошибка, то выполнение кода останавливается и автоматически создается объект-исключение, содержащий описание возникшей ошибки.</p>\n",
    "\n",
    "<p>С практической точки зрения мы можем думать об исключении как о некотором сообщении, которое генерируется интерпретатором Python в силу возникшей ошибки при выполнении кода или из-за некоторых других обстоятельств, близких по своей природе к ошибке выполнения кода. Хотя ошибка и исключение&nbsp;– это не одно и то же (исключение является<br>\n",
    "следствием ошибки), мы обычно отождествляем эти понятия.</p>\n",
    "\n",
    "<p>Для обработки исключительных ситуаций в языке Python используется конструкция <code>try-except</code>. Существуют разные вариации использования этой конструкции. Мы начнем с наиболее простой.</p>\n",
    "\n",
    "<p>После ключевого слова <code>try</code> и двоеточия размещается блок программного кода, который мы подозреваем на предмет возможного возникновения ошибки. Этот код будем называть <strong>контролируемым</strong>. По завершении этого блока указывается ключевое слово <code>except</code> (с двоеточием), после которого идет еще один блок программного кода. Этот код будем называть <strong>кодом обработки ошибки (исключения)</strong>.</p>\n",
    "\n",
    "<p>То есть шаблон такой:</p>\n",
    "\n",
    "<pre><code class=\"language-python hljs\" data-highlighted=\"yes\"><span class=\"hljs-keyword\">try</span>:\n",
    "    <span class=\"hljs-comment\"># контролируемый код</span>\n",
    "<span class=\"hljs-keyword\">except</span>:\n",
    "    <span class=\"hljs-comment\"># код обработки ошибки (исключения)</span></code></pre>\n",
    "\n",
    "<p>Если при выполнении кода в блоке <code>try</code> ошибка не возникла, то код обработки ошибки (исключения) в блоке <code>except</code> выполняться не будет. Если при выполнении кода в блоке <code>try</code> возникла ошибка, то выполнение кода <code>trу</code> блока прекращается, и выполняется код обработки ошибки (исключения) в блоке <code>except</code>. После этого управление передается следующей команде после конструкции <code>try-except</code>.</p>\n",
    "\n",
    "<p>Рассмотрим пример использования инструкции&nbsp;<code>try-except</code>. Контролируемый код содержит считывание данных от пользователя с последующей конвертацией к числовому типу <code>int</code>&nbsp;и выводом частного введенных чисел.</p>\n",
    "\n",
    "<pre><code class=\"language-python hljs\" data-highlighted=\"yes\"><span class=\"hljs-keyword\">try</span>:\n",
    "    num1 = <span class=\"hljs-built_in\">int</span>(<span class=\"hljs-built_in\">input</span>())\n",
    "    num2 = <span class=\"hljs-built_in\">int</span>(<span class=\"hljs-built_in\">input</span>())\n",
    "    <span class=\"hljs-built_in\">print</span>(<span class=\"hljs-string\">'Частное чисел равно'</span>, num1 / num2)\n",
    "<span class=\"hljs-keyword\">except</span>:\n",
    "    <span class=\"hljs-built_in\">print</span>(<span class=\"hljs-string\">'Вы ввели некорректные данные!'</span>)\n",
    "\n",
    "<span class=\"hljs-built_in\">print</span>(<span class=\"hljs-string\">'Работа программы завершена!'</span>)</code></pre>\n",
    "\n",
    "<p>Результат выполнения этого программного кода зависит от того, какие значения будут введены. Рассмотрим несколько ситуаций.</p>\n",
    "\n",
    "<p><strong>Ситуация 1.</strong> На вход подаются два ненулевых целых числа, например <code>10</code> и <code>2</code>. Тогда результатом выполнения кода будет:</p>\n",
    "\n",
    "<pre><code class=\"language-no-highlight hljs\">Частное чисел равно 5.0\n",
    "Работа программы завершена!</code></pre>\n",
    "\n",
    "<p><strong>Ситуация 2.</strong>&nbsp;На вход подаются не числа, а строки, например <code>abc</code> и <code>qwerty</code>. Тогда результатом выполнения кода будет:</p>\n",
    "\n",
    "<pre><code class=\"language-no-highlight hljs\">Вы ввели некорректные данные!\n",
    "Работа программы завершена!</code></pre>\n",
    "\n",
    "<p><strong>Ситуация 3.</strong>&nbsp;На вход подаются два целых числа, второе из которых ноль, например <code>10</code> и <code>0</code>. Тогда результатом выполнения кода будет:</p>\n",
    "\n",
    "<pre><code class=\"language-no-highlight hljs\">Вы ввели некорректные данные!\n",
    "Работа программы завершена!</code></pre>\n",
    "\n",
    "<p><img alt=\"\" name=\"1 копия.png\" src=\"https://sch1998u.mskobr.ru/files/NOVOSTI/30.12.22/20211010105318.png\" width=\"150\">&nbsp; &nbsp;Обратите внимание на последнюю строчку программного кода, она находится вне конструкции <code>try-except</code> и будет выполняться всегда независимо от того, произошла ошибка или нет.</p>\n",
    "\n",
    "<p>Схема обработки ошибок (исключений), описанная выше, во многом проста и удобна. Но она не лишена недостатков. В первую очередь сразу бросается в глаза, что <strong>разные ошибки (исключения) обрабатываются одинаково</strong>. То есть, какая бы ни возникла ошибка (исключение), реакция программы будет одна и та же.</p>\n",
    "\n"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "<h2 style=\"text-align: center;\">Обработка нескольких исключений</h2>\n",
    "\n",
    "<p>Более утонченная обработка ошибок (исключительных ситуаций) подразумевает более индивидуальный подход. Речь идет о том, чтобы обработка ошибок базировалась на типе или характере ошибки. Разумеется, это возможно. Причем описанная выше схема обработки исключений&nbsp;претерпевает минимальные изменения. В&nbsp;конструкции <code>try-except</code> после блока <code>try</code> указывается несколько <code>ехсерt</code> блоков, причем для каждого блока явно указывается тип ошибки (исключения), который обрабатывается в этом блоке. Ключевое слово, определяющее тип ошибки, указывается после ключевого слова <code>except</code> соответствующего блока.</p>\n",
    "\n",
    "<p>То есть шаблон такой:</p>\n",
    "\n",
    "<pre><code class=\"language-python hljs\" data-highlighted=\"yes\"><span class=\"hljs-keyword\">try</span>:\n",
    "    <span class=\"hljs-comment\"># контролируемый код</span>\n",
    "<span class=\"hljs-keyword\">except</span> тип_ошибки_1:\n",
    "    <span class=\"hljs-comment\"># код обработки ошибки (исключения)</span>\n",
    "<span class=\"hljs-keyword\">except</span> тип_ошибки_2:\n",
    "    <span class=\"hljs-comment\"># код обработки ошибки (исключения)</span>\n",
    "...\n",
    "<span class=\"hljs-keyword\">except</span> тип_ошибки_n:\n",
    "    <span class=\"hljs-comment\"># код обработки ошибки (исключения)</span></code></pre>\n",
    "\n",
    "<p>Этот код выполняется следующим образом. Выполняются команды <code>trу</code> блока. Если возникла ошибка, то выполнение команд <code>trу</code> блока прекращается и начинается <strong>последовательный просмотр</strong> <code>ехсерt</code> блоков на предмет совпадения типа ошибки, которая возникла, и типа ошибки, указанного после ключевого слова в <code>ехсерt</code> блоке. Как только совпадение найдено, выполняются команды соответствующего <code>ехсерt</code> блока, после чего управление переходит к команде после конструкции <code>try-except</code>.</p>\n",
    "\n",
    "<p>Если при переборе <code>ехсерt</code> блоков совпадение по типу ошибки не найдено, выполнение кода прекращается и появляется сообщение об ошибке. Если при выполнении <code>trу</code> блока ошибок не было, коды в <code>ехсерt</code> блоках не выполняются.</p>\n",
    "\n",
    "<p>Исправим приведенный выше код с учетом возможности использовать множественные блоки <code>except</code>, указывая тип конкретной ошибки:</p>\n",
    "\n",
    "<pre><code class=\"language-python hljs\" data-highlighted=\"yes\"><span class=\"hljs-keyword\">try</span>:\n",
    "    num1 = <span class=\"hljs-built_in\">int</span>(<span class=\"hljs-built_in\">input</span>())\n",
    "    num2 = <span class=\"hljs-built_in\">int</span>(<span class=\"hljs-built_in\">input</span>())\n",
    "    <span class=\"hljs-built_in\">print</span>(<span class=\"hljs-string\">'Частное чисел равно'</span>, num1 / num2)\n",
    "<span class=\"hljs-keyword\">except</span> ValueError:\n",
    "    <span class=\"hljs-built_in\">print</span>(<span class=\"hljs-string\">'Нужно было ввести числа!'</span>)\n",
    "<span class=\"hljs-keyword\">except</span> ZeroDivisionError:\n",
    "    <span class=\"hljs-built_in\">print</span>(<span class=\"hljs-string\">'На ноль делить нельзя!'</span>)\n",
    "\n",
    "<span class=\"hljs-built_in\">print</span>(<span class=\"hljs-string\">'Работа программы завершена!'</span>)</code></pre>\n",
    "\n",
    "<p>Как мы видим, по сравнению с предыдущим примером изменилась только та часть кода, что связана с <code>ехсерt</code> блоками. Теперь мы имеем два <code>except</code> блока. После первого ключевого слова <code>except</code> указано название <code>ValueError</code>. К типу <code>ValueError</code> относятся ошибки, возникающие при передаче в функцию аргумента с неподдерживаемым значением. Во втором <code>ехсерt</code> блоке обрабатываются ошибки типа&nbsp;<code>ZeroDivisionError</code>. К этому типу относятся ошибки, возникающие при попытке выполнить деление на ноль.</p>\n",
    "\n",
    "<p>Для каждого <code>ехсерt</code> блока предлагается свой программный код (в обоих случаях выводится сообщение с информацией о том, что&nbsp;произошло). При выполнении кода в блоке <code>try</code> если произошла ошибка, тип этой ошибки сначала сопоставляется с типом ошибки <code>ValueError</code> в первом <code>ехсерt</code> блоке. Если совпадение есть, то выполняется код этого блока. Если совпадения нет, проверяется совпадение типа ошибки с классом ошибки <code>ZeroDivisionError</code> во втором <code>ехсерt</code> блоке. Если есть совпадение&nbsp;– выполняется код данного <code>ехсерt</code> блока. Если же и здесь совпадения нет, выполнение программы завершается и появляется автоматически сгенерированное интерпретатором сообщение об ошибке.</p>\n",
    "\n",
    "<p>Стоит также обратить внимание на следующее обстоятельство: обрабатываются в данном случае только ошибки типов&nbsp;<code>ValueError</code> и <code>ZeroDivisionError</code>. Если бы теоретически возникла ошибка какого-то иного типа, то она бы перехвачена не была.</p>\n",
    "\n",
    "<p>В рассмотренном выше примере мы создали для разных типов ошибок разные <code>ехсерt</code> блоки. Иногда приходится для нескольких типов ошибок создавать один <code>ехсерt</code> блок. В этом случае после ключевого слова <code>except</code> в круглых скобках через запятую перечисляются те типы ошибок, для которых выполняется обработка в данном блоке.</p>\n",
    "\n",
    "<pre><code class=\"language-python hljs\" data-highlighted=\"yes\"><span class=\"hljs-keyword\">try</span>:\n",
    "    num1 = <span class=\"hljs-built_in\">int</span>(<span class=\"hljs-built_in\">input</span>())\n",
    "    num2 = <span class=\"hljs-built_in\">int</span>(<span class=\"hljs-built_in\">input</span>())\n",
    "    <span class=\"hljs-built_in\">print</span>(<span class=\"hljs-string\">'Частное чисел равно'</span>, num1 / num2)\n",
    "<span class=\"hljs-keyword\">except</span> (ValueError, IndexError, KeyError):\n",
    "    <span class=\"hljs-built_in\">print</span>(<span class=\"hljs-string\">'Тут обрабатываются сразу три типа ошибок!'</span>)\n",
    "<span class=\"hljs-keyword\">except</span> ZeroDivisionError:\n",
    "    <span class=\"hljs-built_in\">print</span>(<span class=\"hljs-string\">'На ноль делить нельзя!'</span>)\n",
    "<span class=\"hljs-keyword\">except</span>:\n",
    "    <span class=\"hljs-built_in\">print</span>(<span class=\"hljs-string\">'Если не сработал ни один из предыдущих блоков except.'</span>)\n",
    "\n",
    "<span class=\"hljs-built_in\">print</span>(<span class=\"hljs-string\">'Работа программы завершена!'</span>)</code></pre>\n",
    "\n",
    "<p>Обратите внимание также на последний блок <code>except</code>. Он будет обрабатывать любой тип исключения, отличный от указанных выше, причем такой блок должен быть только один, иначе возникнет ошибка (исключение) <code>SyntaxError</code>.</p>\n",
    "\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "numbers = []\n",
    "\n",
    "try:\n",
    "    x = numbers[-1]\n",
    "except:\n",
    "    x = 0\n",
    "except:\n",
    "    x = 1\n",
    "    \n",
    "print(x)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "numbers = []\n",
    "\n",
    "try:\n",
    "    x = numbers[-1]\n",
    "except IndexError:\n",
    "    x = 0\n",
    "except:\n",
    "    x = 1\n",
    "    \n",
    "print(x)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "numbers = []\n",
    "\n",
    "try:\n",
    "    x = numbers[-1]\n",
    "except IndexError:\n",
    "    x = 0\n",
    "except IndexError:\n",
    "    x = 1\n",
    "    \n",
    "print(x)"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "<h2 style=\"text-align: center;\">Основные типы исключений</h2>\n",
    "\n",
    "\n",
    "<ul>\n",
    "\t<li><code>IndexError</code>: возникает, когда индекс (например, для элемента списка) указан неправильно (выходит за границы допустимого диапазона)</li>\n",
    "\t<li><code>KeyError</code>: возникает при неверно указанном ключе словаря</li>\n",
    "\t<li><code>NameError</code>: возникает, если не удается найти переменную с некоторым названием</li>\n",
    "\t<li><code>SyntaxError</code>: возникает при&nbsp;наличии в исходном коде&nbsp;синтаксических ошибок</li>\n",
    "\t<li><code>TypeError</code>: возникает при&nbsp;несоответствии&nbsp;типов, когда для обработки требуется значение определенного типа, а передается значение другого типа</li>\n",
    "\t<li><code>FileNotFoundError</code>: возникает при открытии несуществующего файла</li>\n",
    "\t<li><code>ValueError</code>: возникает, когда в функцию передается аргумент с неподдерживаемым значением</li>\n",
    "\t<li><code>ZeroDivisionError</code>:&nbsp;возникает при попытке выполнить деление на ноль</li>\n",
    "</ul>\n",
    "\n"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "<p>Важно понимать разницу между типами исключений <code>TypeError</code> и <code>ValueError</code>.</p>\n",
    "\n",
    "<p>Исключение&nbsp;<code>TypeError</code> возникает, когда встроенная функция (или операция) применяется к объекту неподходящего типа.</p>\n",
    "\n",
    "<p>Исключение <code>ValueError</code> возникает, когда встроенная функция (или операция) получает аргумент правильного типа, но с неподходящим значением, и ситуация не описывается более точным исключением, например, таким как <code>IndexError</code>.</p>\n",
    "\n",
    "<p> О встроенных типах исключений можно почитать в документации по <a href=\"https://docs.python.org/3/library/exceptions.html\" rel=\"noopener noreferrer nofollow\" target=\"_blank\">ссылке</a>.</p>\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "print('Urban' + 2022)  # TypeError"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "num = int('Urban')  # ValueError"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "numbers = [1, 2, 3, 4, 5]\n",
    "\n",
    "try:\n",
    "    print(numbers[1] + numbers[5])\n",
    "except:\n",
    "    print('Произошла ошибка')\n",
    "    \n",
    "print('Завершение программы')"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "try:\n",
    "    numbers = [1, 2, 3, 4] + '5'\n",
    "    print(numbers)\n",
    "except ZeroDivisionError:\n",
    "    print('ZeroDivisionError')\n",
    "except ValueError:\n",
    "    print('ValueError')\n",
    "\n",
    "print('Программа завершилась штатно.')"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "<h2 style=\"text-align: center;\">Необязательный блок else</h2>\n",
    "\n",
    "<p>Помимо блоков <code>try</code> и <code>except</code>, в инструкции <code>try-except</code>&nbsp;может также использоваться необязательный блок&nbsp;<code>else</code>.</p>\n",
    "\n",
    "<p>Блок&nbsp;<code>else</code> размещается после последнего <code>ехсерt</code> блока и содержит программный код, который <strong>выполняется только в том случае</strong>, если при выполнении кода в <code>trу</code> блоке ошибок (исключений) не было.</p>\n",
    "\n",
    "<p>Шаблон инструкции&nbsp;<code>try-except</code> в этом случае такой:</p>\n",
    "\n",
    "<pre><code class=\"language-python hljs\" data-highlighted=\"yes\"><span class=\"hljs-keyword\">try</span>:\n",
    "    <span class=\"hljs-comment\"># контролируемый код</span>\n",
    "<span class=\"hljs-keyword\">except</span> тип_ошибки_1:\n",
    "    <span class=\"hljs-comment\"># код обработки ошибки (исключения)</span>\n",
    "<span class=\"hljs-keyword\">except</span> тип_ошибки_2:\n",
    "    <span class=\"hljs-comment\"># код обработки ошибки (исключения)</span>\n",
    "...\n",
    "<span class=\"hljs-keyword\">except</span> тип_ошибки_n:\n",
    "    <span class=\"hljs-comment\"># код обработки ошибки (исключения)</span>\n",
    "<span class=\"hljs-keyword\">else</span>:\n",
    "    <span class=\"hljs-comment\"># код для случая, если ошибки (исключения) не было</span></code></pre>\n",
    "\n",
    "<p>Рассмотрим программный код:</p>\n",
    "\n",
    "<pre><code class=\"language-python hljs\" data-highlighted=\"yes\"><span class=\"hljs-keyword\">try</span>:\n",
    "    num = <span class=\"hljs-built_in\">int</span>(<span class=\"hljs-built_in\">input</span>())\n",
    "    <span class=\"hljs-built_in\">print</span>(<span class=\"hljs-string\">'Квадрат числа равен:'</span>, num ** <span class=\"hljs-number\">2</span>)\n",
    "<span class=\"hljs-keyword\">except</span> ValueError:\n",
    "    <span class=\"hljs-built_in\">print</span>(<span class=\"hljs-string\">'Вы ввели некорректные данные!'</span>)\n",
    "<span class=\"hljs-keyword\">else</span>:\n",
    "    <span class=\"hljs-built_in\">print</span>(<span class=\"hljs-string\">'Ошибки не произошло!'</span>)\n",
    "\n",
    "<span class=\"hljs-built_in\">print</span>(<span class=\"hljs-string\">'Работа программы завершена!'</span>)</code></pre>\n",
    "\n",
    "<p>Результат выполнения этого программного кода зависит от того, какое значение будет введено. Рассмотрим две ситуации.</p>\n",
    "\n",
    "<p><strong>Ситуация 1.</strong> На вход подается целое число, например <code>10</code>. Тогда результатом выполнения кода будет:</p>\n",
    "\n",
    "<pre><code class=\"language-no-highlight hljs\">Квадрат числа равен: 100\n",
    "Ошибки не произошло!\n",
    "Работа программы завершена!</code></pre>\n",
    "\n",
    "<p><strong>Ситуация 2.</strong>&nbsp;На вход подается не число, а строка, например,&nbsp;<code>abc</code>.&nbsp;Тогда результатом выполнения кода будет:</p>\n",
    "\n",
    "<pre><code class=\"language-no-highlight hljs\">Вы ввели некорректные данные!\n",
    "Работа программы завершена!</code></pre>\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "letters = {'a': 'A', 'b': 'B', 'c': 'C'}\n",
    "result = None\n",
    "\n",
    "try:\n",
    "    result = letters['B']\n",
    "except:\n",
    "    print('Произошла ошибка')\n",
    "else:\n",
    "    print('Ошибок не произошло')\n",
    "    \n",
    "print(result)"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "<h2 style=\"text-align: center;\">Необязательный блок finally</h2>\n",
    "\n",
    "<p>Помимо необязательного блока <code>else</code>, в&nbsp;инструкции <code>try-except</code>&nbsp;можно также использовать необязательный блок <code>finally</code>.</p>\n",
    "\n",
    "<p>Блок&nbsp;<code>finally</code> размещается после последнего <code>ехсерt</code> блока, либо после блока <code>else</code>, если он присутствует, и содержит программный код, который <strong>выполняется в любом случае</strong>, независимо от того, возникла ошибка (исключение) при выполнении кода <code>trу</code> блока или нет.</p>\n",
    "\n",
    "<p>Шаблон инструкции&nbsp;<code>try-except</code> в этом случае такой:</p>\n",
    "\n",
    "<pre><code class=\"language-python hljs\" data-highlighted=\"yes\"><span class=\"hljs-keyword\">try</span>:\n",
    "    <span class=\"hljs-comment\"># контролируемый код</span>\n",
    "<span class=\"hljs-keyword\">except</span> тип_ошибки_1:\n",
    "    <span class=\"hljs-comment\"># код обработки ошибки (исключения)</span>\n",
    "<span class=\"hljs-keyword\">except</span> тип_ошибки_2:\n",
    "    <span class=\"hljs-comment\"># код обработки ошибки (исключения)</span>\n",
    "...\n",
    "<span class=\"hljs-keyword\">except</span> тип_ошибки_n:\n",
    "    <span class=\"hljs-comment\"># код обработки ошибки (исключения)</span>\n",
    "<span class=\"hljs-keyword\">finally</span>:\n",
    "    <span class=\"hljs-comment\"># код, который выполняется всегда</span></code></pre>\n",
    "\n",
    "<p>Рассмотрим программный код:</p>\n",
    "\n",
    "<pre><code class=\"language-python hljs\" data-highlighted=\"yes\"><span class=\"hljs-keyword\">try</span>:\n",
    "    num = <span class=\"hljs-built_in\">int</span>(<span class=\"hljs-built_in\">input</span>())\n",
    "    <span class=\"hljs-built_in\">print</span>(<span class=\"hljs-string\">'Квадрат числа равен:'</span>, num ** <span class=\"hljs-number\">2</span>)\n",
    "<span class=\"hljs-keyword\">except</span> ValueError:\n",
    "    <span class=\"hljs-built_in\">print</span>(<span class=\"hljs-string\">'Вы ввели некорректные данные!'</span>)\n",
    "<span class=\"hljs-keyword\">finally</span>:\n",
    "    <span class=\"hljs-built_in\">print</span>(<span class=\"hljs-string\">'Блок кода выполняется всегда!'</span>)\n",
    "\n",
    "<span class=\"hljs-built_in\">print</span>(<span class=\"hljs-string\">'Работа программы завершена!'</span>)</code></pre>\n",
    "\n",
    "<p>Результат выполнения этого программного кода зависит от того, какое значение будет введено. Рассмотрим две ситуации.</p>\n",
    "\n",
    "<p><strong>Ситуация 1.</strong> На вход подается целое число, например,&nbsp;<code>10</code>. Тогда результатом выполнения кода будет:</p>\n",
    "\n",
    "<pre><code class=\"language-no-highlight hljs\">Квадрат числа равен: 100\n",
    "Блок кода выполняется всегда!\n",
    "Работа программы завершена!</code></pre>\n",
    "\n",
    "<p><strong>Ситуация 2.</strong>&nbsp;На вход подается не число, а строка, например,&nbsp;<code>abc</code>.&nbsp;Тогда результатом выполнения кода будет:</p>\n",
    "\n",
    "<pre><code class=\"language-no-highlight hljs\">Вы ввели некорректные данные!\n",
    "Блок кода выполняется всегда!\n",
    "Работа программы завершена!</code></pre>\n",
    "\n",
    "<p>Блок <code>finally</code> особенно удобен при работе с файлами, которые нужно обязательно закрывать, независимо от того, произошла ошибка (исключение) или нет.</p>\n",
    "\n",
    "<p>Приведенный ниже код:</p>\n",
    "\n",
    "<pre><code class=\"language-python hljs\" data-highlighted=\"yes\"><span class=\"hljs-keyword\">try</span>:\n",
    "    file = <span class=\"hljs-built_in\">open</span>(<span class=\"hljs-string\">'data.txt'</span>, encoding=<span class=\"hljs-string\">'utf-8'</span>)\n",
    "    <span class=\"hljs-keyword\">try</span>:\n",
    "        text = file.read()\n",
    "    <span class=\"hljs-keyword\">except</span>:\n",
    "        <span class=\"hljs-built_in\">print</span>(<span class=\"hljs-string\">'При чтении из файла произошла ошибка!'</span>)\n",
    "    <span class=\"hljs-keyword\">else</span>:\n",
    "        <span class=\"hljs-built_in\">print</span>(<span class=\"hljs-string\">'Чтение из файла прошло успешно!'</span>)\n",
    "    <span class=\"hljs-keyword\">finally</span>:\n",
    "        file.close()\n",
    "<span class=\"hljs-keyword\">except</span> FileNotFoundError:\n",
    "    <span class=\"hljs-built_in\">print</span>(<span class=\"hljs-string\">'Файл с указанным именем не найден!'</span>)</code></pre>\n",
    "\n",
    "<p>демонстрирует возможность использования блока <code>finally</code>. В этом коде файл будет закрыт в любом случае, вне зависимости от того, произошла ошибка или нет. Обратите также внимание на вложенность блоков <code>try-except</code>.</p>\n",
    "\n",
    "<p>Блоки <code>try-except</code> можно вкладывать один в другой.&nbsp;Python никак нас не ограничивает в количестве таких вложений.</p>\n",
    "\n",
    "<p>Блок&nbsp;<code>finally</code>&nbsp;может также использоваться без блоков <code>except</code> и <code>else</code>. В этом случае, если в блоке <code>try</code> возникает ошибка (исключение), то сначала выполняется блок <code>finally</code>, а затем ошибка (исключение) продолжает «всплывание» к обработчику более высокого уровня.</p>\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "try:\n",
    "    file = open('data.txt', 'w', encoding='utf-8')\n",
    "    try:\n",
    "        text = file.read()\n",
    "    finally:\n",
    "        print('What?')\n",
    "        file.close()\n",
    "except FileNotFoundError:\n",
    "    print('Файл с указанным именем не найден!')\n",
    "except:\n",
    "    print('Произошла ошибка!')"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "try:\n",
    "    for i in range(3):\n",
    "        print(i)\n",
    "        break\n",
    "finally:\n",
    "    print('Завершение программы')"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "letters = {'a': 'A', 'b': 'B', 'c': 'C'}\n",
    "\n",
    "try:\n",
    "    print(letters['b'])\n",
    "except:\n",
    "    print('Произошла ошибка')\n",
    "else:\n",
    "    print('Ошибок не произошло')\n",
    "finally:\n",
    "    print('Завершение программы')"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "def numbers():\n",
    "    try:\n",
    "        value = 100\n",
    "        return value\n",
    "    except:\n",
    "        value = 200\n",
    "    else:\n",
    "        value = 300\n",
    "    finally:\n",
    "        value = 400\n",
    "        return value\n",
    "        \n",
    "print(numbers())"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "<h2 style=\"text-align: center;\">Общий шаблон инструкции try-except</h2>\n",
    "\n",
    "<p>Общий шаблон инструкции&nbsp;<code>try-except</code>,&nbsp;включая все блоки, имеет вид:</p>\n",
    "\n",
    "<pre><code class=\"language-python hljs\" data-highlighted=\"yes\"><span class=\"hljs-keyword\">try</span>:\n",
    "    <span class=\"hljs-comment\"># контролируемый код</span>\n",
    "<span class=\"hljs-keyword\">except</span> тип_ошибки_1:\n",
    "    <span class=\"hljs-comment\"># код обработки ошибки (исключения)</span>\n",
    "<span class=\"hljs-keyword\">except</span> тип_ошибки_2:\n",
    "    <span class=\"hljs-comment\"># код обработки ошибки (исключения)</span>\n",
    "...\n",
    "<span class=\"hljs-keyword\">except</span> тип_ошибки_n:\n",
    "    <span class=\"hljs-comment\"># код обработки ошибки (исключения)</span>\n",
    "<span class=\"hljs-keyword\">else</span>:\n",
    "    <span class=\"hljs-comment\"># код для случая, если ошибки не было</span>\n",
    "<span class=\"hljs-keyword\">finally</span>:\n",
    "    <span class=\"hljs-comment\"># код, который выполняется всегда</span></code></pre>\n",
    "\n"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "\n",
    "<p>Необходимо заметить, что при наличии ошибки (исключения) и отсутствии блока <code>except</code>, инструкции внутри блока <code>finally</code> будут выполнены, но ошибка (исключение) не будет обработана. Она продолжит «всплывание» к обработчику более высокого уровня. Если пользовательский обработчик отсутствует, то управление передается обработчику по умолчанию, который прерывает выполнение программы и выводит сообщение об ошибке.</p>\n",
    "\n",
    "<pre><code class=\"language-python hljs\" data-highlighted=\"yes\"><span class=\"hljs-keyword\">try</span>:\n",
    "    х = <span class=\"hljs-number\">10</span> / <span class=\"hljs-number\">0</span>\n",
    "<span class=\"hljs-keyword\">finally</span>:\n",
    "    <span class=\"hljs-built_in\">print</span>(<span class=\"hljs-string\">'Блoк finally'</span>)</code></pre>\n",
    "\n",
    "<p>выводит:</p>\n",
    "\n",
    "<pre><code class=\"language-no-highlight hljs\">Блoк finally\n",
    "Traceback (most recent call last):\n",
    "  File \"main.py\", line 2, in &lt;module&gt;\n",
    "    х = 10 / 0\n",
    "ZeroDivisionError: division by zero</code></pre>\n",
    "\n",
    "<p>Инструкции внутри блока <code>finally</code> будут выполнены, даже если блок&nbsp;<code>try</code> содержит <code>break, continue, return</code>.</p>\n",
    "\n",
    "<p>Следующая особенность работы блока <code>finally</code> связана с обработкой ошибок (исключений) внутри функций. Нужно знать, что блок <code>finally</code> выполняется до <code>return</code>.</p>\n",
    "\n",
    "<p>Приведенный ниже код:</p>\n",
    "\n",
    "<pre><code class=\"language-python hljs\" data-highlighted=\"yes\"><span class=\"hljs-keyword\">def</span> <span class=\"hljs-title function_\">func</span>():\n",
    "    <span class=\"hljs-keyword\">try</span>:\n",
    "        <span class=\"hljs-keyword\">return</span> <span class=\"hljs-number\">10</span>\n",
    "    <span class=\"hljs-keyword\">finally</span>:\n",
    "        <span class=\"hljs-built_in\">print</span>(<span class=\"hljs-string\">'Выполняется блок finally!'</span>)\n",
    "\n",
    "<span class=\"hljs-built_in\">print</span>(func())</code></pre>\n",
    "\n",
    "<p>выводит:</p>\n",
    "\n",
    "<pre><code class=\"language-no-highlight hljs\">Выполняется блок finally!\n",
    "10</code></pre>\n",
    "\n",
    "<p>Интересна ситуация, когда возврат из функции (<code>return</code>) осуществляется как в блоке <code>try</code>, так и в блоке <code>finally</code>. Поскольку блок <code>finally</code> выполняется до <code>return</code>, то результирующее значение будет получено именно из блока <code>finally</code>.</p>\n",
    "\n",
    "<p>Приведенный ниже код:</p>\n",
    "\n",
    "<pre><code class=\"language-python hljs\" data-highlighted=\"yes\"><span class=\"hljs-keyword\">def</span> <span class=\"hljs-title function_\">func</span>():\n",
    "    <span class=\"hljs-keyword\">try</span>:\n",
    "        <span class=\"hljs-keyword\">return</span> <span class=\"hljs-number\">10</span>\n",
    "    <span class=\"hljs-keyword\">finally</span>:\n",
    "        <span class=\"hljs-keyword\">return</span> <span class=\"hljs-number\">20</span>\n",
    "\n",
    "<span class=\"hljs-built_in\">print</span>(func())</code></pre>\n",
    "\n",
    "<p>выводит:</p>\n",
    "\n",
    "<pre><code class=\"language-no-highlight hljs\">20</code></pre>\n",
    "\n",
    "<p>Язык Python поддерживает протокол менеджеров контекста с помощью ключевого слова <code>with</code>.&nbsp;Этот протокол гарантирует выполнение завершающих действий (например, закрытие файла) вне зависимости от того, произошла ошибка (исключение) внутри блока кода или нет.&nbsp;</p>\n",
    "\n",
    "<p>Приведенный код:</p>\n",
    "\n",
    "<pre><code class=\"language-python hljs\" data-highlighted=\"yes\"><span class=\"hljs-keyword\">with</span> <span class=\"hljs-built_in\">open</span>(<span class=\"hljs-string\">'data.txt'</span>, <span class=\"hljs-string\">'r'</span>, encoding=<span class=\"hljs-string\">'utf-8'</span>) <span class=\"hljs-keyword\">as</span> file:\n",
    "    text = file.read()</code></pre>\n",
    "\n",
    "<p>примерно равнозначен коду:</p>\n",
    "\n",
    "<pre><code class=\"language-python hljs\" data-highlighted=\"yes\"><span class=\"hljs-keyword\">try</span>:\n",
    "    file = <span class=\"hljs-built_in\">open</span>(<span class=\"hljs-string\">'data.txt'</span>, <span class=\"hljs-string\">'r'</span>, encoding=<span class=\"hljs-string\">'utf-8'</span>)\n",
    "    <span class=\"hljs-keyword\">try</span>:\n",
    "        text = file.read()\n",
    "    <span class=\"hljs-keyword\">finally</span>:\n",
    "        file.close()\n",
    "<span class=\"hljs-keyword\">except</span>:\n",
    "    <span class=\"hljs-keyword\">pass</span></code></pre>\n",
    "\n",
    "<p>Предпочтение всегда стоит отдавать менеджерам контекста (ключевое слово <code>with</code>), а не блоку <code>try-finally</code>.</p>\n",
    "\n",
    "<p>Рассмотрим следующий код:</p>\n",
    "\n",
    "<pre><code class=\"language-python hljs\" data-highlighted=\"yes\"><span class=\"hljs-keyword\">def</span> <span class=\"hljs-title function_\">f</span>():\n",
    "    <span class=\"hljs-keyword\">try</span>:\n",
    "        x = <span class=\"hljs-number\">10</span>\n",
    "        <span class=\"hljs-keyword\">return</span> x\n",
    "    <span class=\"hljs-keyword\">finally</span>:\n",
    "        x = <span class=\"hljs-number\">20</span>\n",
    "          \n",
    "<span class=\"hljs-built_in\">print</span>(f())</code></pre>\n",
    "\n",
    "<p>Как мы знаем, код в блоке&nbsp;<code>finally</code> выполняется до оператора <code>return</code>, поэтому можно предположить, что после выполнения приведенного выше кода будет выведено значение <code>20</code>, хотя на самом деле выведено будет <code>10</code>. Дело в том, что оператор <code>return</code> сохраняет значение возвращаемой переменной, поэтому дальнейшее присвоение переменной <code>x</code> нового значения не повлечет за собой изменения возвращаемого функцией значения.</p>\n",
    "\n",
    "<p>Проиллюстрировать это можно следующий образом:</p>\n",
    "\n",
    "<p style=\"text-align: center;\"><img alt=\"\" height=\"184\" name=\"Новый проект (1).png\" src=\"https://ucarecdn.com/b0cd88e9-9285-4fb1-93b7-88840d5a660a/\" width=\"721\"></p>\n",
    "\n",
    "<p>Для большего понимания рассмотрим следующий код:</p>\n",
    "\n",
    "<pre><code data-highlighted=\"yes\" class=\"hljs language-csharp\"><span class=\"hljs-function\">def <span class=\"hljs-title\">f</span>():\n",
    "    <span class=\"hljs-keyword\">try</span>:\n",
    "        x</span> = [<span class=\"hljs-number\">10</span>]\n",
    "        <span class=\"hljs-keyword\">return</span> x\n",
    "    <span class=\"hljs-keyword\">finally</span>:\n",
    "        x.append(<span class=\"hljs-number\">20</span>)\n",
    "          \n",
    "print(f())</code></pre>\n",
    "\n",
    "<p>Теперь в переменной <code>x</code> содержится изменяемый объект&nbsp;— список <code>[10]</code>. Оператор <code>return</code> сохраняет данный список в качестве возвращаемого значения, но мы по-прежнему можем к нему обратиться и, например, добавить в него значение <code>20</code>.&nbsp;Так как оператор <code>return</code>&nbsp;по-прежнему ссылается на этот же список, после выполнения приведенного выше кода будет выведено&nbsp;<code>[10, 20]</code>.</p>\n",
    "\n",
    "<ul>\n",
    "\t<li>ветка на сайте&nbsp;stackoverflow с обсуждением данного вопроса доступна по&nbsp;<a href=\"https://stackoverflow.com/questions/62678765/finally-always-runs-just-before-the-return-in-try-block-then-why-update-in-fina\" rel=\"noopener noreferrer nofollow\" target=\"_blank\">ссылке</a></li>\n",
    "\t<li>полезная статья об устройстве&nbsp;переменных в Python доступна по <a href=\"https://nedbatchelder.com/text/names.html\" rel=\"noopener noreferrer nofollow\" target=\"_blank\">ссылке</a></li>\n",
    "</ul>"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "x = 20\n",
    "\n",
    "\n",
    "def f():\n",
    "    try:\n",
    "        global x\n",
    "        x = 10\n",
    "        return x\n",
    "    finally:\n",
    "        x = 30\n",
    "        print(f'В блоке finally {x = }, но из-за return в try нам вернется...')\n",
    "\n",
    "\n",
    "print(f())\n",
    "print(f'Однако так как глобально х мы в последний раз меняли в finally, то теперь {x = } все же.')"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "<h2 style=\"text-align: center;\">Иерархия исключений</h2>\n",
    "\n",
    "<p>В Python присутствует строгая иерархия исключений, вершиной которой является тип&nbsp;<code>BaseException</code>.</p>\n",
    "\n",
    "<p>Тип <code>BaseException</code>&nbsp;является классом самого верхнего уровня и базовым для всех прочих классов исключений.</p>\n",
    "\n",
    "<p><strong>Дерево встроенных исключений</strong> выглядит так:</p>\n",
    "\n",
    "<pre><code class=\"language-no-highlight hljs\">BaseException\n",
    " +-- SystemExit\n",
    " +-- KeyboardInterrupt\n",
    " +-- GeneratorExit\n",
    " +-- Exception\n",
    "      +-- StopIteration\n",
    "      +-- StopAsyncIteration\n",
    "      +-- ArithmeticError\n",
    "      |    +-- FloatingPointError\n",
    "      |    +-- OverflowError\n",
    "      |    +-- ZeroDivisionError\n",
    "      +-- AssertionError\n",
    "      +-- AttributeError\n",
    "      +-- BufferError\n",
    "      +-- EOFError\n",
    "      +-- ImportError\n",
    "           +-- ModuleNotFoundError\n",
    "      +-- LookupError\n",
    "      |    +-- IndexError\n",
    "      |    +-- KeyError\n",
    "      +-- MemoryError\n",
    "      +-- NameError\n",
    "      |    +-- UnboundLocalError\n",
    "      +-- OSError\n",
    "      |    +-- BlockingIOError\n",
    "      |    +-- ChildProcessError\n",
    "      |    +-- ConnectionError\n",
    "      |    |    +-- BrokenPipeError\n",
    "      |    |    +-- ConnectionAbortedError\n",
    "      |    |    +-- ConnectionRefusedError\n",
    "      |    |    +-- ConnectionResetError\n",
    "      |    +-- FileExistsError\n",
    "      |    +-- FileNotFoundError\n",
    "      |    +-- InterruptedError\n",
    "      |    +-- IsADirectoryError\n",
    "      |    +-- NotADirectoryError\n",
    "      |    +-- PermissionError\n",
    "      |    +-- ProcessLookupError\n",
    "      |    +-- TimeoutError\n",
    "      +-- ReferenceError\n",
    "      +-- RuntimeError\n",
    "      |    +-- NotImplementedError\n",
    "      |    +-- RecursionError\n",
    "      +-- SyntaxError\n",
    "      |    +-- IndentationError\n",
    "      |         +-- TabError\n",
    "      +-- SystemError\n",
    "      +-- TypeError\n",
    "      +-- ValueError\n",
    "      |    +-- UnicodeError\n",
    "      |         +-- UnicodeDecodeError\n",
    "      |         +-- UnicodeEncodeError\n",
    "      |         +-- UnicodeTranslateError\n",
    "      +-- Warning\n",
    "           +-- DeprecationWarning\n",
    "           +-- PendingDeprecationWarning\n",
    "           +-- RuntimeWarning\n",
    "           +-- SyntaxWarning\n",
    "           +-- UserWarning\n",
    "           +-- FutureWarning\n",
    "           +-- ImportWarning\n",
    "           +-- UnicodeWarning\n",
    "           +-- BytesWarning\n",
    "           +-- ResourceWarning</code></pre>\n",
    "\n",
    "<p>По дереву видно, что исключения&nbsp;<code>IndexError</code>&nbsp;и&nbsp;<code>KeyError</code>&nbsp;являются <strong>потомками (наследниками)</strong> исключения&nbsp;<code>LookupError</code>, которое является потомком&nbsp;<code>Exception</code>. В то время как исключения&nbsp;<code>FloatingPointError,&nbsp;OverflowError</code> и&nbsp;<code>ZeroDivisionError</code> являются потомками исключения <code>ArithmeticError</code>.<br>\n",
    "<br>\n",
    "<img alt=\"\" name=\"1 копия.png\" src=\"https://sch1998u.mskobr.ru/files/NOVOSTI/30.12.22/20211010105318.png\" width=\"150\">&nbsp; &nbsp;Тип <code>Exception</code>&nbsp;– базовый класс для большинства встроенных в Python исключений. Именно его, а не <code>BaseException</code>, необходимо наследовать при создании пользовательского класса исключения.</p>\n",
    "\n",
    "<p>Для проверки родства классов исключений можно использовать встроенную функцию&nbsp;<code>issubclass()</code>, которая указывает на то, является ли некоторый класс потомком указанного класса или нет.</p>\n",
    "\n",
    "<p>Приведенный ниже код:</p>\n",
    "\n",
    "<pre><code class=\"language-python hljs\" data-highlighted=\"yes\"><span class=\"hljs-built_in\">print</span>(<span class=\"hljs-built_in\">issubclass</span>(IndexError, LookupError))\n",
    "<span class=\"hljs-built_in\">print</span>(<span class=\"hljs-built_in\">issubclass</span>(KeyError, Exception))\n",
    "<span class=\"hljs-built_in\">print</span>(<span class=\"hljs-built_in\">issubclass</span>(ZeroDivisionError, ArithmeticError))\n",
    "\n",
    "<span class=\"hljs-built_in\">print</span>(<span class=\"hljs-built_in\">issubclass</span>(IndexError, ArithmeticError))\n",
    "<span class=\"hljs-built_in\">print</span>(<span class=\"hljs-built_in\">issubclass</span>(FloatingPointError, OverflowError))</code></pre>\n",
    "\n",
    "<p>выводит:</p>\n",
    "\n",
    "<pre><code class=\"language-no-highlight hljs\">True\n",
    "True\n",
    "True\n",
    "False\n",
    "False</code></pre>\n",
    "\n",
    "<p>Важно помнить, что если у нас используется несколько блоков&nbsp;<code>except</code>, то первыми нужно указывать наиболее конкретные. Иначе мы можем оказаться в ситуации вроде этой:</p>\n",
    "\n",
    "<pre><code class=\"language-python hljs\" data-highlighted=\"yes\"><span class=\"hljs-keyword\">try</span>:\n",
    "    nums = [<span class=\"hljs-number\">10</span>, <span class=\"hljs-number\">5</span>, <span class=\"hljs-number\">20</span>, <span class=\"hljs-number\">25</span>]\n",
    "    <span class=\"hljs-built_in\">print</span>(nums[<span class=\"hljs-number\">100</span>])\n",
    "<span class=\"hljs-keyword\">except</span> Exception:\n",
    "    <span class=\"hljs-built_in\">print</span>(<span class=\"hljs-string\">'Произошла ошибка!'</span>)\n",
    "<span class=\"hljs-keyword\">except</span> (KeyError, IndexError):\n",
    "    <span class=\"hljs-built_in\">print</span>(<span class=\"hljs-string\">'Ошибка связанная с индексом!'</span>)\n",
    "</code></pre>\n",
    "\n",
    "<p>Здесь первый блок&nbsp;<code>except</code>&nbsp;отлавливает вообще все исключения, ведь любое конкретное исключение наследуется от типа&nbsp;<code>Exception</code>. Второй блок&nbsp;<code>except</code>&nbsp;не имеет шанса хоть раз быть выполненным.</p>\n",
    "\n",
    "<p><img alt=\"\" name=\"1 копия.png\" src=\"https://sch1998u.mskobr.ru/files/NOVOSTI/30.12.22/20211010105318.png\" width=\"150\">&nbsp; &nbsp;Обработчик исключений может поймать не&nbsp;только указанные типы исключений, но&nbsp;и&nbsp;всех их&nbsp;потомков.</p>\n",
    "\n"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "<h2 style=\"text-align: center;\">Работа с объектом возбужденного исключения</h2>\n",
    "\n",
    "<p>Если нужен доступ к сгенерированному исключению как к&nbsp;объекту, то используется специальный синтаксис.</p>\n",
    "\n",
    "<p>Приведенный ниже код:</p>\n",
    "\n",
    "<pre><code class=\"language-python hljs\" data-highlighted=\"yes\"><span class=\"hljs-keyword\">try</span>:\n",
    "    nums = [<span class=\"hljs-number\">10</span>, <span class=\"hljs-number\">5</span>, <span class=\"hljs-number\">20</span>, <span class=\"hljs-number\">25</span>]\n",
    "    <span class=\"hljs-built_in\">print</span>(nums[<span class=\"hljs-number\">100</span>])\n",
    "<span class=\"hljs-keyword\">except</span> (KeyError, IndexError) <span class=\"hljs-keyword\">as</span> err:    <span class=\"hljs-comment\"># записываем сгенерированное исключение в переменную err</span>\n",
    "    <span class=\"hljs-built_in\">print</span>(err)\n",
    "    <span class=\"hljs-built_in\">print</span>(<span class=\"hljs-built_in\">type</span>(err))</code></pre>\n",
    "\n",
    "<p>выводит:</p>\n",
    "\n",
    "<pre><code class=\"language-1c hljs\" data-highlighted=\"yes\">list index out of range\n",
    "&lt;class 'IndexError'&gt;</code></pre>\n",
    "\n",
    "<p>В&nbsp;данном примере в&nbsp;переменную <code>err</code>&nbsp;попадает объект типа&nbsp;<code>IndexError</code>.</p>\n",
    "\n",
    "<p>Посмотреть все атрибуты объекта сгенерированного исключения можно с помощью встроенной функции <code>dir()</code>.</p>\n",
    "\n",
    "<p>Приведенный ниже код:</p>\n",
    "\n",
    "<pre><code class=\"language-python hljs\" data-highlighted=\"yes\"><span class=\"hljs-keyword\">try</span>:\n",
    "    <span class=\"hljs-built_in\">print</span>(<span class=\"hljs-number\">1</span> / <span class=\"hljs-number\">0</span>)\n",
    "<span class=\"hljs-keyword\">except</span> ZeroDivisionError <span class=\"hljs-keyword\">as</span> err:\n",
    "    <span class=\"hljs-built_in\">print</span>(<span class=\"hljs-built_in\">dir</span>(err))</code></pre>\n",
    "\n",
    "<p>выводит:</p>\n",
    "\n",
    "<pre><code class=\"language-no-highlight hljs\">['__cause__', '__class__', '__context__', '__delattr__', '__dict__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__le__', '__lt__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__setstate__', '__sizeof__', '__str__', '__subclasshook__', '__suppress_context__', '__traceback__', 'args', 'with_traceback']</code></pre>\n",
    "\n",
    "<p>Наибольший интерес представляет из себя атрибут <code>args</code>, о котором будет рассказано ниже.</p>\n",
    "\n",
    "<p><img alt=\"\" name=\"1 копия.png\" src=\"https://sch1998u.mskobr.ru/files/NOVOSTI/30.12.22/20211010105318.png\" width=\"150\">&nbsp; &nbsp;В имени <code>err</code> нет ничего особенного. Это просто имя, которое мы выбрали для примеров. Можно использовать любое имя по своему выбору. Обычно используют имена <code>err, exp, e</code>.</p>\n",
    "\n",
    "<p>Если при обработке всех исключений одним блоком <code>except</code> мы хотим получить доступ к объекту исключения, то нужно явно указать его тип.</p>\n",
    "\n",
    "<p>Приведенный ниже код:</p>\n",
    "\n",
    "<pre><code class=\"language-python hljs\" data-highlighted=\"yes\"><span class=\"hljs-keyword\">try</span>:\n",
    "    х = <span class=\"hljs-number\">1</span> / <span class=\"hljs-number\">0</span>\n",
    "<span class=\"hljs-keyword\">except</span> <span class=\"hljs-keyword\">as</span> err:\n",
    "    <span class=\"hljs-built_in\">print</span>(err)</code></pre>\n",
    "\n",
    "<p>синтаксически неверен.</p>\n",
    "\n",
    "<p>Для исправления кода мы пишем:</p>\n",
    "\n",
    "<pre><code class=\"language-python hljs\" data-highlighted=\"yes\"><span class=\"hljs-keyword\">try</span>:\n",
    "    х = <span class=\"hljs-number\">1</span> / <span class=\"hljs-number\">0</span>\n",
    "<span class=\"hljs-keyword\">except</span> Exception <span class=\"hljs-keyword\">as</span> err:\n",
    "    <span class=\"hljs-built_in\">print</span>(err)</code></pre>\n",
    "\n",
    "\n"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "<p>Для получения информации об исключении можно воспользоваться функцией <code>exc_infо()</code> из модуля <code>sys</code>.&nbsp;Данная функция возвращает кортеж из трех значений: типа исключения, значения и объекта с трассировочной информацией&nbsp;об исключении, которое в данный момент обрабатывается.</p>\n",
    "\n",
    "<p>Приведенный ниже код:</p>\n",
    "\n",
    "<pre><code class=\"language-python hljs\" data-highlighted=\"yes\"><span class=\"hljs-keyword\">from</span> sys <span class=\"hljs-keyword\">import</span> exc_info\n",
    "\n",
    "<span class=\"hljs-keyword\">try</span>:\n",
    "    х = <span class=\"hljs-number\">1</span> / <span class=\"hljs-number\">0</span>\n",
    "<span class=\"hljs-keyword\">except</span> Exception <span class=\"hljs-keyword\">as</span> err:\n",
    "    <span class=\"hljs-built_in\">print</span>(exc_info())</code></pre>\n",
    "\n",
    "<p>выводит:</p>\n",
    "\n",
    "<pre><code class=\"language-no-highlight hljs\">(&lt;class 'ZeroDivisionError'&gt;, ZeroDivisionError('division by zero'), &lt;traceback object at 0x000001BEEF80E840&gt;)</code></pre>\n",
    "\n",
    "<p>Преобразовать эти значения в удобочитаемый вид позволяет модуль <code>traceback</code>.</p>\n",
    "\n",
    "<p>Таблица основных типов исключений.</p>\n",
    "\n",
    "<table align=\"center\" border=\"1\" cellpadding=\"1\" cellspacing=\"1\">\n",
    "\t<thead>\n",
    "\t\t<tr>\n",
    "\t\t\t<th>Тип исключения</th>\n",
    "\t\t\t<th>Описание</th>\n",
    "\t\t</tr>\n",
    "\t</thead>\n",
    "\t<tbody>\n",
    "\t\t<tr>\n",
    "\t\t\t<td style=\"text-align: center;\"><code>BaseException</code></td>\n",
    "\t\t\t<td>является классом самого верхнего уровня и базовым для всех прочих<br>\n",
    "\t\t\tклассов исключений</td>\n",
    "\t\t</tr>\n",
    "\t\t<tr>\n",
    "\t\t\t<td style=\"text-align: center;\"><code>Exception</code></td>\n",
    "\t\t\t<td>базовый класс для большинства встроенных в Python исключений. Именно<br>\n",
    "\t\t\tего, а не <code>BaseException</code>, необходимо наследовать при создании пользовательского класса<br>\n",
    "\t\t\tисключения</td>\n",
    "\t\t</tr>\n",
    "\t\t<tr>\n",
    "\t\t\t<td style=\"text-align: center;\"><code>AssertionError</code></td>\n",
    "\t\t\t<td>возбуждается инструкцией <code>assert</code></td>\n",
    "\t\t</tr>\n",
    "\t\t<tr>\n",
    "\t\t\t<td style=\"text-align: center;\"><code>AttributeError</code></td>\n",
    "\t\t\t<td>возбуждается при попытке&nbsp;обращения к несуществующему атрибуту объекта</td>\n",
    "\t\t</tr>\n",
    "\t\t<tr>\n",
    "\t\t\t<td style=\"text-align: center;\"><code>EOFError</code></td>\n",
    "\t\t\t<td>возбуждается функцией <code>input()</code> при достижении конца файла с вводными&nbsp;данными</td>\n",
    "\t\t</tr>\n",
    "\t\t<tr>\n",
    "\t\t\t<td style=\"text-align: center;\"><code>ImportError</code></td>\n",
    "\t\t\t<td>возбуждается, если невозможно импортировать модуль или пакет</td>\n",
    "\t\t</tr>\n",
    "\t\t<tr>\n",
    "\t\t\t<td style=\"text-align: center;\"><code>IndexError</code></td>\n",
    "\t\t\t<td>возбуждается при попытке получить элемент коллекции по несуществующему индексу</td>\n",
    "\t\t</tr>\n",
    "\t\t<tr>\n",
    "\t\t\t<td style=\"text-align: center;\"><code>KeyError</code></td>\n",
    "\t\t\t<td>возбуждается при попытке получить элемент коллекции по несуществующему ключу</td>\n",
    "\t\t</tr>\n",
    "\t\t<tr>\n",
    "\t\t\t<td style=\"text-align: center;\"><code>MemoryError</code></td>\n",
    "\t\t\t<td>возбуждается, если интерпретатору существенно не хватает оперативной памяти</td>\n",
    "\t\t</tr>\n",
    "\t\t<tr>\n",
    "\t\t\t<td style=\"text-align: center;\"><code>NameError</code></td>\n",
    "\t\t\t<td>возбуждается при попытке обратиться к необъявленной переменной</td>\n",
    "\t\t</tr>\n",
    "\t\t<tr>\n",
    "\t\t\t<td style=\"text-align: center;\"><code>TypeError</code></td>\n",
    "\t\t\t<td>возбуждается при&nbsp;несоответствии&nbsp;типов</td>\n",
    "\t\t</tr>\n",
    "\t\t<tr>\n",
    "\t\t\t<td style=\"text-align: center;\"><code>ValueError</code></td>\n",
    "\t\t\t<td>возбуждается при передаче в функцию аргумента&nbsp;с неподдерживаемым значением</td>\n",
    "\t\t</tr>\n",
    "\t\t<tr>\n",
    "\t\t\t<td style=\"text-align: right;\"><code>ZeroDivisionError</code></td>\n",
    "\t\t\t<td>возбуждается при попытке выполнить деление на ноль</td>\n",
    "\t\t</tr>\n",
    "\t\t<tr>\n",
    "\t\t\t<td style=\"text-align: right;\"><code>NotImplementedError</code></td>\n",
    "\t\t\t<td>возбуждается, если&nbsp;наследник класса не переопределил метод, который должен был переопределить</td>\n",
    "\t\t</tr>\n",
    "\t</tbody>\n",
    "</table>\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "import traceback\n",
    "import logging\n",
    "\n",
    "logging.basicConfig(filename=\"error.log\", level=logging.ERROR)\n",
    "\n",
    "def faulty_function():\n",
    "    return 1 / 0\n",
    "\n",
    "try:\n",
    "    faulty_function()\n",
    "except ZeroDivisionError:\n",
    "    print(traceback.format_exc())\n",
    "    logging.error(\"Исключение:\", exc_info=True)\n",
    "\n",
    "print('Программа работает дальше...')"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "<div id=\"ember21083\" class=\"html-content rich-text-viewer ember-view\" data-processed=\"\"><!----><span><h2 style=\"text-align: center;\">Возбуждение исключений</h2>\n",
    "\n",
    "<p>Мы можем заставить и наш код также возбудить исключение.</p>\n",
    "\n",
    "<p>Для возбуждения исключения используется оператор <code>raise</code>. В качестве аргумента оператор <code>raise</code> использует экземпляр класса, унаследованного от <code>Exception</code>. Класс указывает на тип исключения, а аргумент, передаваемый конструктору этого исключения, обычно описывает подробности возникновения исключительной ситуации.</p>\n",
    "\n",
    "<p>Если возбуждаемые пользователем исключения не перехватываются, то они распространяются вплоть до стандартного обработчика исключений и прекращают работу программы с выводом стандартного сообщения об ошибке.</p>\n",
    "\n",
    "<p><img alt=\"\" name=\"1 копия.png\" src=\"https://sch1998u.mskobr.ru/files/NOVOSTI/30.12.22/20211010105318.png\" width=\"150\">&nbsp; &nbsp;Возбуждаемые пользователем исключения перехватываются тем же способом, что и исключения, которые возбуждает интерпретатор Python.</p>\n",
    "\n",
    "<p>Приведенный ниже код:</p>\n",
    "\n",
    "<pre><code class=\"language-python hljs\" data-highlighted=\"yes\"><span class=\"hljs-keyword\">try</span>:\n",
    "    <span class=\"hljs-keyword\">raise</span> IndexError(<span class=\"hljs-string\">'ошибочка'</span>)             <span class=\"hljs-comment\"># возбуждение исключения вручную</span>\n",
    "<span class=\"hljs-keyword\">except</span> Exception <span class=\"hljs-keyword\">as</span> err:\n",
    "    <span class=\"hljs-built_in\">print</span>(err)\n",
    "    <span class=\"hljs-built_in\">print</span>(<span class=\"hljs-built_in\">type</span>(err)) </code></pre>\n",
    "\n",
    "<p>выводит:</p>\n",
    "\n",
    "<pre><code class=\"language-1c hljs\" data-highlighted=\"yes\">ошибочка\n",
    "&lt;class 'IndexError'&gt;</code></pre>\n",
    "\n",
    "<p>Приведем еще один пример:</p>\n",
    "\n",
    "<pre><code class=\"language-python hljs\" data-highlighted=\"yes\"><span class=\"hljs-keyword\">def</span> <span class=\"hljs-title function_\">get_month_name</span>(<span class=\"hljs-params\">index</span>):\n",
    "    <span class=\"hljs-keyword\">if</span> <span class=\"hljs-keyword\">not</span> index.isdigit():\n",
    "        <span class=\"hljs-keyword\">raise</span> TypeError(<span class=\"hljs-string\">'Аргумент должен быть числом.'</span>)\n",
    "    <span class=\"hljs-keyword\">if</span> <span class=\"hljs-built_in\">int</span>(index) &lt; <span class=\"hljs-number\">1</span> <span class=\"hljs-keyword\">or</span> <span class=\"hljs-built_in\">int</span>(index) &gt; <span class=\"hljs-number\">12</span>:\n",
    "        <span class=\"hljs-keyword\">raise</span> ValueError(<span class=\"hljs-string\">'Аргумент должен быть целым числом от 1 до 12.'</span>)\n",
    "     ...</code></pre>\n",
    "\n",
    "<p>При создании объекта исключения мы можем указать в конструкторе подробности возникновения исключительной ситуации. Конструктор любого исключения принимает переменное количество аргументов. Для того чтобы получить указанные значения, мы используем атрибут <code>args</code>, который является кортежем.</p>\n",
    "\n",
    "<p>Приведенный ниже код:</p>\n",
    "\n",
    "<pre><code class=\"language-python hljs\" data-highlighted=\"yes\"><span class=\"hljs-keyword\">try</span>:\n",
    "    x, y = <span class=\"hljs-number\">10</span>, <span class=\"hljs-number\">0</span>\n",
    "    <span class=\"hljs-keyword\">if</span> y == <span class=\"hljs-number\">0</span>:\n",
    "        <span class=\"hljs-keyword\">raise</span> ZeroDivisionError(<span class=\"hljs-string\">'Произошло деление на ноль.'</span>)\n",
    "<span class=\"hljs-keyword\">except</span> ZeroDivisionError <span class=\"hljs-keyword\">as</span> err:\n",
    "    <span class=\"hljs-built_in\">print</span>(err)\n",
    "    <span class=\"hljs-built_in\">print</span>(err.args)\n",
    "    <span class=\"hljs-built_in\">print</span>(<span class=\"hljs-built_in\">type</span>(err.args))</code></pre>\n",
    "\n",
    "<p>выводит:</p>\n",
    "\n",
    "<pre><code class=\"language-no-highlight hljs\">Произошло деление на ноль.\n",
    "('Произошло деление на ноль.',)\n",
    "&lt;class 'tuple'&gt;</code></pre>\n",
    "\n",
    "<p><img alt=\"\" name=\"1 копия.png\" src=\"https://sch1998u.mskobr.ru/files/NOVOSTI/30.12.22/20211010105318.png\" width=\"150\">&nbsp; &nbsp;При печати объекта исключения автоматически происходит вызов функции <code>str()</code>.</p>\n",
    "\n",
    "<p>Оператор возбуждения исключений&nbsp;<code>raise</code>&nbsp;имеет несколько вариантов формата:</p>\n",
    "\n",
    "<ul>\n",
    "\t<li><code>raise</code> &lt;экземпляр класса&gt;</li>\n",
    "\t<li><code>raise</code> &lt;название класса&gt;</li>\n",
    "\t<li><code>raise</code> &lt;экземпляр или название класса&gt; <code>from</code> &lt;объект исключения&gt;</li>\n",
    "\t<li><code>raise</code></li>\n",
    "</ul>\n",
    "\n",
    "<p><strong>В первом варианте</strong> оператора <code>raise</code> указывается экземпляр класса возбуждаемого исключения с аргументами при необходимости.</p>\n",
    "\n",
    "<p>Пример:</p>\n",
    "\n",
    "<pre><code class=\"language-python hljs\" data-highlighted=\"yes\"><span class=\"hljs-keyword\">raise</span> ValueError(<span class=\"hljs-string\">'Oпиcaниe исключения'</span>)</code></pre>\n",
    "\n",
    "<p><strong>Во втором варианте</strong> оператора <code>raise</code> указывается только название класса исключения.</p>\n",
    "\n",
    "<p>Пример:</p>\n",
    "\n",
    "<pre><code class=\"language-python hljs\" data-highlighted=\"yes\"><span class=\"hljs-keyword\">raise</span> ValueError                       <span class=\"hljs-comment\"># эквивалентно: raise ValueError()</span></code></pre>\n",
    "\n",
    "<p><strong>В третьем варианте</strong> оператора <code>raise</code> сначала указывается экземпляр класса или просто название класса, а потом объект исключения, на основании которого создается новое исключение. В этом случае объект исходного исключения сохраняется в атрибуте <code>__cause__</code>. При обработке вложенных исключений эти данные используются для вывода информации не только о последнем исключении, но и о первоначальном исключении.</p>\n",
    "\n",
    "<p>Пример:</p>\n",
    "\n",
    "<pre><code class=\"language-python hljs\" data-highlighted=\"yes\"><span class=\"hljs-keyword\">try</span>:\n",
    "    х = <span class=\"hljs-number\">1</span> / <span class=\"hljs-number\">0</span>\n",
    "<span class=\"hljs-keyword\">except</span> Exception <span class=\"hljs-keyword\">as</span> err:\n",
    "   <span class=\"hljs-keyword\">raise</span> ZeroDivisionError(<span class=\"hljs-string\">'Описание исключения'</span>) <span class=\"hljs-keyword\">from</span> err</code></pre>\n",
    "\n"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "<h2 style=\"text-align: center;\">Повторное возбуждение исключения</h2>\n",
    "\n",
    "<p><strong>В четвертом варианте</strong> оператора <code>raise</code>&nbsp;мы повторно возбуждаем и пробрасываем выше последнее перехваченное исключение.</p>\n",
    "\n",
    "<p>Пример:</p>\n",
    "\n",
    "<pre><code class=\"language-python hljs\" data-highlighted=\"yes\"><span class=\"hljs-keyword\">try</span>:\n",
    "    х = <span class=\"hljs-number\">1</span> / <span class=\"hljs-number\">0</span>\n",
    "<span class=\"hljs-keyword\">except</span> Exception <span class=\"hljs-keyword\">as</span> err:\n",
    "    <span class=\"hljs-built_in\">print</span>(err)                  <span class=\"hljs-comment\"># каким-то образом обработали перехваченное исключение</span>\n",
    "    <span class=\"hljs-keyword\">raise</span>                       <span class=\"hljs-comment\"># пробрасываем исключение выше</span></code></pre>\n",
    "\n"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "<h2 style=\"text-align: center;\">Примечания</h2>\n",
    "\n",
    "<p><strong>Примечание 1.</strong> Возбуждение исключения в коде похоже на <code>return</code>, только на его глобальную версию, завершающую все функции в порядке, обратном тому, в котором они вызывались. Если исключение будет возбуждено, но не будет перехвачено, то есть как-то обработано, вся программа так и завершится.</p>\n",
    "\n",
    "<p><strong>Примечание 2.</strong> Сам механизм исключений достаточно медленный, поэтому, например, не&nbsp;очень хорошей идеей будет возбуждать исключение внутри цикла, когда мы&nbsp;точно знаем, что их&nbsp;будет достаточно большое количество.</p>\n",
    "\n",
    "<p><strong>Примечание 3.</strong> В ситуации, когда мы перехватываем&nbsp;исключение, делаем некие действия, а затем пробрасываем его выше, нужно использовать следующий код:</p>\n",
    "\n",
    "<pre><code class=\"language-python hljs\" data-highlighted=\"yes\"><span class=\"hljs-keyword\">try</span>:\n",
    "    х = <span class=\"hljs-number\">1</span> / <span class=\"hljs-number\">0</span>\n",
    "<span class=\"hljs-keyword\">except</span> Exception <span class=\"hljs-keyword\">as</span> err:\n",
    "    <span class=\"hljs-built_in\">print</span>(err)                  <span class=\"hljs-comment\"># каким-то образом обработали перехваченное исключение</span>\n",
    "    <span class=\"hljs-keyword\">raise</span>                       <span class=\"hljs-comment\"># пробрасываем исключение выше</span></code></pre>\n",
    "\n",
    "<p>Использовать код:</p>\n",
    "\n",
    "<pre><code class=\"language-python hljs\" data-highlighted=\"yes\"><span class=\"hljs-keyword\">try</span>:\n",
    "    х = <span class=\"hljs-number\">1</span> / <span class=\"hljs-number\">0</span>\n",
    "<span class=\"hljs-keyword\">except</span> Exception <span class=\"hljs-keyword\">as</span> err:\n",
    "    <span class=\"hljs-built_in\">print</span>(err)\n",
    "    <span class=\"hljs-keyword\">raise</span> err</code></pre>\n",
    "\n",
    "<p>не рекомендуется, так как мы получим возбуждение нового исключения, пусть даже и представляющего старый объект. Возбуждение нового исключения повлечет за собой потерю&nbsp;информации о месте возникновения изначального исключения.</p>\n",
    "\n",
    "<p>Просто пишите&nbsp;<code>raise</code>&nbsp;— так будет заново возбуждено последнее перехваченное исключение с сохранением нужной информации.</p>\n",
    "\n",
    "<p><strong>Примечание 4.</strong>&nbsp;Как уже говорилось ранее, при создании объекта исключения мы можем указать в конструкторе подробности возникновения исключительной ситуации.&nbsp;Конструктор исключения принимает переменное количество аргументов.</p>\n",
    "\n",
    "<p>Приведенный ниже код:</p>\n",
    "\n",
    "<pre><code class=\"language-python hljs\" data-highlighted=\"yes\"><span class=\"hljs-keyword\">try</span>:\n",
    "    <span class=\"hljs-keyword\">raise</span> ValueError(<span class=\"hljs-string\">'Произошла ошибка'</span>)\n",
    "<span class=\"hljs-keyword\">except</span> ValueError <span class=\"hljs-keyword\">as</span> e:\n",
    "    <span class=\"hljs-built_in\">print</span>(e)</code></pre>\n",
    "\n",
    "<p>выводит:</p>\n",
    "\n",
    "<pre><code class=\"language-python hljs\" data-highlighted=\"yes\">Произошла ошибка</code></pre>\n",
    "\n",
    "<p>Примечательно то, что при передаче переменной с исключением в функцию <code>print()</code> происходит вывод именно тех аргументов, которые были указаны при создании объекта исключения. И если таких аргументов было передано несколько, они будут выведены все в виде кортежа.</p>\n",
    "\n",
    "<p>Приведенный ниже код:</p>\n",
    "\n",
    "<pre><code class=\"language-python hljs\" data-highlighted=\"yes\"><span class=\"hljs-keyword\">try</span>:\n",
    "    <span class=\"hljs-keyword\">raise</span> ValueError(<span class=\"hljs-string\">'Ой'</span>, <span class=\"hljs-string\">'Произошла ошибка'</span>)\n",
    "<span class=\"hljs-keyword\">except</span> ValueError <span class=\"hljs-keyword\">as</span> e:\n",
    "    <span class=\"hljs-built_in\">print</span>(e)</code></pre>\n",
    "\n",
    "<p>выводит:</p>\n",
    "\n",
    "<pre><code class=\"language-no-highlight hljs\">('Ой', 'Произошла ошибка')</code></pre>\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "def inner_function():\n",
    "    try:\n",
    "        1 / 0\n",
    "    except ZeroDivisionError:\n",
    "        print(\"Исключение обработано внутри, но пробрасываю выше!\")\n",
    "        raise\n",
    "\n",
    "def outer_function():\n",
    "    try:\n",
    "        inner_function()\n",
    "    except ZeroDivisionError as err:\n",
    "        print(\"Исключение обработано на уровне outer_function\")\n",
    "\n",
    "\n",
    "outer_function()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "def inner_function():\n",
    "    try:\n",
    "        1 / 0\n",
    "    except ZeroDivisionError:\n",
    "        print(\"Исключение обработано внутри, но пробрасываю выше!\")\n",
    "        raise\n",
    "\n",
    "def outer_function():\n",
    "    try:\n",
    "        inner_function()\n",
    "    except ZeroDivisionError as err:\n",
    "        print(\"Исключение обработано на уровне outer_function\")\n",
    "        raise ValueError(\"Нкито\", \"не лбюит\", \"ошибаьтся\") from err\n",
    "\n",
    "\n",
    "outer_function()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "def inner_function():\n",
    "    try:\n",
    "        1 / 0\n",
    "    except ZeroDivisionError:\n",
    "        print(\"Исключение обработано внутри, но пробрасываю выше!\")\n",
    "        raise\n",
    "\n",
    "def outer_function():\n",
    "    try:\n",
    "        inner_function()\n",
    "    except ZeroDivisionError as err:\n",
    "        print(\"Исключение обработано на уровне outer_function\")\n",
    "        raise ValueError(\"Нкито\", \"не лбюит\", \"ошибаьтся\") from err\n",
    "\n",
    "try:\n",
    "    outer_function()\n",
    "except ValueError as e:\n",
    "    print(e)"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "vscode_env",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.12.3"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
